/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./templates/**/*.html",
    "./static/js/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d7e3fb",
        "surface": "#faf9ff",
        "on-primary-fixed": "#001848",
        "error": "#ba1a1a",
        "inverse-surface": "#1d3054",
        "on-primary": "#ffffff",
        "surface-container-low": "#f1f3ff",
        "primary": "#003d9b",
        "secondary-fixed-dim": "#bbc7de",
        "on-tertiary-fixed-variant": "#812800",
        "on-primary-fixed-variant": "#0040a2",
        "on-surface-variant": "#434654",
        "primary-fixed-dim": "#b2c5ff",
        "outline-variant": "#c3c6d6",
        "surface-dim": "#ccdaff",
        "surface-tint": "#0c56d0",
        "on-background": "#051a3e",
        "tertiary": "#7b2600",
        "on-secondary": "#ffffff",
        "surface-variant": "#d8e2ff",
        "on-secondary-fixed": "#101c2d",
        "tertiary-fixed-dim": "#ffb59b",
        "surface-container-highest": "#d8e2ff",
        "on-tertiary-container": "#ffc6b2",
        "on-error": "#ffffff",
        "primary-container": "#0052cc",
        "error-container": "#ffdad6",
        "secondary-container": "#d4e0f8",
        "secondary": "#535f73",
        "surface-container-high": "#e1e8ff",
        "surface-bright": "#faf9ff",
        "on-secondary-container": "#576377",
        "surface-container": "#e9edff",
        "tertiary-fixed": "#ffdbcf",
        "on-secondary-fixed-variant": "#3b475b",
        "inverse-on-surface": "#edf0ff",
        "tertiary-container": "#a33500",
        "on-primary-container": "#c4d2ff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#380d00",
        "on-surface": "#051a3e",
        "primary-fixed": "#dae2ff",
        "surface-container-lowest": "#ffffff",
        "outline": "#737685",
        "background": "#faf9ff",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "margin-desktop": "32px",
        "lg": "24px",
        "md": "16px",
        "sm": "8px",
        "xs": "4px",
        "margin-mobile": "16px",
        "base": "4px",
        "xl": "32px",
        "gutter": "16px",
        "toolbar-width": "64px",
        "sidebar-width": "280px",
      },
      fontFamily: {
        "headline-md": ["Inter", "system-ui", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Inter", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "system-ui", "sans-serif"],
        "headline-sm": ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "label-caps": ["Inter", "system-ui", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "label-mono": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};
